pipeline {
  agent { label 'AGENT-01' }
  when {
    // Khi merge PR vào nhánh develop
    allOf {
      // not { changeRequest() }
      expression {
        return !changeRequest()
      }
      branch 'develop'
    }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh './mvnw -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        sh './mvnw test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    stage('Deploy') {
      when {
        expression { return !changeRequest() }  // Chỉ deploy sau khi merge
      }
      steps {
        script {
          def selectedEnv = input(
            id: 'DeployEnv', message: 'Chọn môi trường để deploy:',
            parameters: [
              choice(name: 'ENV', choices: ['dev', 'staging', 'prod'], description: 'Chọn môi trường')
            ]
          )
          echo "Đang deploy lên môi trường: ${selectedEnv.toUpperCase()}"

          switch (selectedEnv) {
            case 'dev':
              if (env.BRANCH_NAME != 'develop') {
                error "Không thể deploy DEV từ nhánh ${env.BRANCH_NAME}. Phải là develop."
              }
              echo "Deploying to DEV"
              // sh './scripts/deploy-dev.sh'
              break

            case 'staging':
              if (env.BRANCH_NAME != 'staging') {
                error "Không thể deploy STAGING từ nhánh ${env.BRANCH_NAME}. Phải là staging."
              }
              echo "Deploying to STAGING"
              // sh './scripts/deploy-staging.sh'
              break

            case 'prod':
              if (env.BRANCH_NAME != 'main') {
                error "Không thể deploy PROD từ nhánh ${env.BRANCH_NAME}. Phải là main."
              }
              input message: "Xác nhận deploy lên PROD?"
              echo "Deploying to PROD"
              // sh './scripts/deploy-prod.sh'
              break

            default:
              echo "Không có môi trường phù hợp. Bỏ qua deploy."
          }
        }
      }
    }
  }
}