pipeline {
  agent { label 'AGENT-01' }

  environment {
    AWS_DEFAULT_REGION = 'eu-west-1'
    AWS_CREDS = credentials('aws-creds')
  }

  tools {
    terraform 'terraform1.12-linux'
  }

  stages {
    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      when {
        changeset "**/.infastructure/**"
      }
      steps {
        dir('.infastructure') {
          sh '''
            terraform init -input=false
          '''
        }
      }
    }

    stage('Terraform Format and Validate') {
      when {
        changeset "**/.infastructure/**"
      }
      steps {
        dir('.infastructure') {
          sh 'terraform fmt'
          sh 'terraform validate -no-color'
        }
      }
    }

    stage('Terraform Plan') {
      when {
        changeset "**/.infastructure/**"
      }
      steps {
        dir('.infastructure') {
          sh 'terraform plan -no-color -input=false'
        }
      }
    }

    stage('Manual Approval') {
      when {
        changeset "**/.infastructure/**"
      }
      steps {
        timeout(time: 1, unit: 'HOURS') {
          input message: 'Apply changes?'
        }
      }
    }

    stage('Terraform Apply') {
      when {
        changeset "**/.infastructure/**"
      }
      steps {
        dir('.infastructure') {
          sh 'terraform apply --auto-approve'
        }
      }
    }
  }
}