pipeline {
  agent { label 'AGENT-01' }
  when {
    // Khi có PR, PR từ nhánh feature, thay đổi trong src hoặc pom.xml
    allOf {
      changeRequest()
      expression { return env.CHANGE_BRANCH ==~ /^feature\/.*/ }
      anyOf {
        changeset "**/src/**"
        changeset "**/pom.xml"
      }
    }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh './mvnw -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        sh './mvnw test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
  }
}